### ISSUE TITLE
Field with no 'show' attribute

### ISSUE THREAD

**Issue by alset0326** [CrabeDeFrance/rtshark#1]
An ICMP Layer may have this field

```xml
 <field name="data" value="0a"/>
```

which would cause an err `"xml lookup error: no key 'show' in ' name=\"data\" value=\"0a\"'"`

Maybe we should consider 'value' as another key as 'show' do?

See [pyshark](https://github.com/KimiNewt/pyshark/blob/master/src/pyshark/packet/fields.py#L14) for field handling

**Comment by CrabeDeFrance** [comment]
Hi, thanks for reporting this issue and the pyshark tip.
I added the same algorithm in version 2.2.0. 
Closing this issue for now,, please open it again if you still have some troubles.
