### ISSUE TITLE
Feature Request: Parse fields with child data

### ISSUE THREAD

**Issue by DennisNemec** [CrabeDeFrance/rtshark#12]
Hello there,

first of all thanks for this amazing crate which makes my life easier with parsing PCAPs! In the context of my Bachelor's Thesis I use this crate for analyzing Bluetooth LE data. I noticed that only "fields" are parsed that don't have any child data. In terms of XML it means that fields need to have following representation: `<field ... />`. In my case I could not get a specific field because it had some child data (`<field ...>...</field>`).

For example:

```xml

<field name="btcommon.eir_ad.entry.data" showname="Data: <data>" size="8" pos="39" show="<some data>" value="<some data>">
          <field name="_ws.expert" showname="Expert Info (Note/Undecoded): Undecoded" size="0" pos="39">
            <field name="btcommon.eir_ad.undecoded" showname="Undecoded" size="0" pos="0" show="" value=""/>
            <field name="_ws.expert.message" showname="Message: Undecoded" hide="yes" size="0" pos="0" show="Undecoded"/>
            <field name="_ws.expert.severity" showname="Severity level: Note" size="0" pos="0" show="4194304"/>
            <field name="_ws.expert.group" showname="Group: Undecoded" size="0" pos="0" show="83886080"/>
          </field>
  </field>

```

I was not able to retrieve the field with the name `btcommon.eir_ad.entry.data`. 

I propose to add the functionality to parse fields that have child data.

Best regards,
Dennis

**Comment by DennisNemec** [comment]
I implemented it already.

[allow-fields-with-childs.zip](https://github.com/CrabeDeFrance/rtshark/files/13253048/allow-fields-with-childs.zip)

**Comment by CrabeDeFrance** [comment]
Thanks for fixing this !
