### ISSUE TITLE
Is it possible to pass in an `SSLKEYLOGFILE`?

### ISSUE THREAD

**Issue by larseggert** [CrabeDeFrance/rtshark#19]
Is it possible to pass in an `SSLKEYLOGFILE`, to decrypt and analyze TLS traffic?

**Comment by evanrittenhouse** [comment]
Yes, there's a [`keylog_file`](https://docs.rs/rtshark/2.8.0/rtshark/struct.RTSharkBuilderReady.html#method.keylog_file) method which will decrypt the packets for you

**Comment by CrabeDeFrance** [comment]
Hi Lars, is it ok for you ? Can I close this issue ?
